### ISSUE TITLE
Erreur 404 lorsquon tente daccder a https://raw.githubusercontent.com/WalkingMachine/ros_install/master/ros_core.rosinstall

### ISSUE THREAD

**Issue by alex2603** [WalkingMachine/sara_install#26]
Le script install_ros_core.bash chie a la ligne wget https://raw.githubusercontent.com/WalkingMachine/ros_install/master/ros_core.rosinstall

Il n'y a pas de fichier de ce nom dans la branche master, mais il y a un dans ork_dev

**Comment by JeffCousineau** [comment]
Ça fait environ 2 ans qu'on a pas touché à sara_install :P 
Je vais essayer de faire un update et d'actualiser les package utilisé

**Comment by maximeconnolly** [comment]
Utilise http://wiki.ros.org/rosinstall_generator a la place de les faires a la main comme dans le vieux temps
