### ISSUE TITLE
unknown command

### ISSUE THREAD

**Issue by salco** [WalkingMachine/sara_install#7]
in the sara_installer.bash you add this line:
source ~/sara_ws/devel/setup.bash
In the ~/.bashrc but when I check the folder sara_ws I have only one folder and it's src

Is it a missing file or a bad command?

**Comment by maximeconnolly** [comment]
That means that the catkin_make has failed. The devel and build folder are generated on the catkin_make.

**Comment by salco** [comment]
yeah I get that but why you add it before the catkin_make is execute you should put in the ~/,bashrc only if the build succeed.

**Comment by maximeconnolly** [comment]
Yeah that would be the best course of action

**Comment by salco** [comment]
I will correct that in my pull request I've just finish it.
