### ISSUE TITLE
Permettre l'installation ailleur que dans le Home

### ISSUE THREAD

**Issue by gortium** [WalkingMachine/sara_install#9]
Julien à voulu faire les chose proprement est c'est créé un folder WM pour y mettre tout ses chose du club dedans, mais quand il a roulé sara_install dans sont folder, le scrip a fail et a créé sara_ws au Home et a mit le contenue du src dans son folder.

**Comment by Philippe117** [comment]
La nouvelle structure de sara_install est maintenant mieux encapsulé. Ce bug n'arrivera plus.
